# Generated by Django 3.1.1 on 2020-10-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PBZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBZ.product'),
        ),
    ]
