from django.urls import path
from PBZ import views

urlpatterns = [
    path('',views.form_user, name='form_user'),
    path('form_registration',views.form_registration,name='form_reg'),
    path('logout',views.do_logout,name='logout'),
    path('registration',views.registration,name='registration'),
    path('login',views.login_user, name='login'),
    path('home_page', views.home_page, name='home_page'),
    path('product_page', views.page_product, name='product_page'),
    path('form_product', views.form_product, name='form_product'),
    path('create_product', views.create_product, name='create_product'),
    path('edit_page', views.edit_page, name='edit_page'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete_page', views.delete_page, name='delete_page'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('show_category', views.show_category_of_product, name='show_category'),
    path('page_waybill', views.page_waybill, name='page_waybill'),
    path('form_waybill', views.form_waybill, name='form_waybill'),
    path('form_customer', views.form_customer, name='form_customer'),
    path('create_customer', views.create_customer, name='create_customer'),
    path('form_destination', views.form_destination, name='form_destination'),
    path('create_destination', views.create_destination, name='create_destination'),
    path('create_waybill', views.create_waybill, name='create_waybill'),
    path('show_customer', views.show_customer, name='show_customer'),
    path('edit_waybill_page', views.edit_waybill_page, name='edit_waybill_page'),
    path('edit_waybill/<int:waybill_id>/', views.edit_waybill, name='edit_waybill'),
    path('delete_waybill_page', views.page_delete_waybill, name='delete_waybill_page'),
    path('delete_waybill/<int:waybill_id>/', views.delete_waybill, name='delete_waybill'),
    path('show_price_change', views.show_price_change, name='price_change'),
    path('additional', views.page_additional, name='additional'),
    path('page_customer', views.page_customer, name='page_customer'),
    path('page_destination', views.page_destination, name='page_destination'),
    path('edit_customer_page', views.customer_edit_page, name='edit_customer_page'),
    path('edit_customer/<int:customer_id>/', views.edit_customer, name='edit_customer'),
    path('delete_page_customer', views.delete_page_customer, name='delete_page_customer'),
    path('delete_customer/<int:customer_id>/', views.delete_customer, name='delete_customer'),
    path('edit_destination_page', views.destination_edit_page, name='edit_destination_page'),
    path('edit_destination/<int:destination_id>/', views.edit_destination, name='edit_destination'),
    path('delete_destination_page', views.delete_page_destination, name='delete_destination_page'),
    path('delete_destination/<int:destination_id>/', views.delete_destination, name='delete_destination'),
    path('create_customer_add',views.create_customer_add,name='create_customer_add'),
    path('create_customer_form',views.create_customer_form,name='create_customer_form'),
    path('create_destination_form',views.create_destination_page,name='create_destination_form'),
    path('create_destination_add',views.create_destination_add,name='create_destination_add')

]
